services:
  - type: web
    name: waymate-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && export NODE_ENV=production && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
