import React,{useState} from 'react';
import {Alert,Image,KeyboardAvoidingView,Platform,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '../auth/AuthContext';
import {Button,Card,Input} from '../components/ui';
import {colors} from '../theme/theme';

export default function LoginScreen(){const {sendOtp}=useAuth();const [phone,setPhone]=useState('+91 ');const [confirm,setConfirm]=useState<any>(null);const [code,setCode]=useState('');const [loading,setLoading]=useState(false);const doOtp=async()=>{if(phone.replace(/\D/g,'').length<10)return Alert.alert('Enter your mobile number','Use a valid Indian mobile number.');setLoading(true);try{setConfirm(await sendOtp(phone.replace(/\s/g,'')))}catch(e:any){Alert.alert('Could not send OTP',e.message)}finally{setLoading(false)}};const verify=async()=>{setLoading(true);try{await confirm.confirm(code)}catch(e:any){Alert.alert('Invalid OTP','Check the code and try again.')}finally{setLoading(false)}};return <SafeAreaView style={s.root}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content}><View style={s.brand}><Image source={require('../../waymate-horizontal.png')} style={s.logo}/><View style={s.brandLine}><Ionicons name="shield-checkmark" size={14} color={colors.green}/><Text style={s.brandText}>Bengaluru's trusted commute network</Text></View></View>{!confirm?<><Text style={s.title}>Commute smarter{`\n`}together.</Text><Text style={s.copy}>Find verified rides, book your seat or share your empty seats with people going your way.</Text><Card style={s.loginCard}><Input label="MOBILE NUMBER" icon="phone-portrait-outline" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><Button title={loading?'Sending OTP…':'Continue with mobile'} icon="arrow-forward" disabled={loading} onPress={doOtp}/><Text style={s.terms}>By continuing, you agree to WayMate's Terms, Privacy Policy and safety guidelines.</Text></Card><View style={s.bullets}>{[['shield-checkmark','Verified identity'],['car-outline','Verified vehicles'],['navigate','Live trip tracking']].map(([i,t])=><View key={t} style={s.bullet}><Ionicons name={i as any} size={17} color={colors.greenDark}/><Text style={s.bulletText}>{t}</Text></View>)}</View></>:<><Text style={s.title}>Verify your number.</Text><Text style={s.copy}>Enter the 6-digit OTP sent to {phone}.</Text><Card style={s.loginCard}><Input label="OTP" icon="keypad-outline" keyboardType="number-pad" maxLength={6} value={code} onChangeText={setCode}/><Button title={loading?'Verifying…':'Verify & continue'} icon="checkmark" disabled={loading||code.length<6} onPress={verify}/><Button secondary title="Change mobile number" onPress={()=>setConfirm(null)}/></Card></>}</ScrollView></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{flexGrow:1,padding:22,justifyContent:'center'},brand:{alignItems:'center',marginBottom:26},logo:{width:210,height:86,resizeMode:'contain'},brandLine:{flexDirection:'row',alignItems:'center',gap:6,marginTop:-8},brandText:{fontSize:10,fontWeight:'800',color:colors.greenDark},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:colors.navy,letterSpacing:-.7},copy:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:10,marginBottom:18},loginCard:{padding:18},terms:{fontSize:9,lineHeight:14,color:colors.muted,textAlign:'center',marginTop:8},bullets:{gap:12,marginTop:4},bullet:{flexDirection:'row',alignItems:'center',gap:10},bulletText:{fontSize:12,fontWeight:'800',color:colors.navy}});
