import React,{useCallback,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Loading,RouteRow} from '../components/ui';
import {colors} from '../theme/theme';
import {bookingApi,requestApi,rideApi} from '../api/services';

export default function MyRidesScreen({navigation}:any){const [tab,setTab]=useState<'booked'|'hosted'>('booked');const [bookings,setBookings]=useState<any[]>([]);const [rides,setRides]=useState<any[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);Promise.all([bookingApi.my(),rideApi.my()]).then(([b,r])=>{setBookings(b);setRides(r)}).catch(e=>Alert.alert('Could not load rides',e.message)).finally(()=>setLoading(false))},[]);useFocusEffect(useCallback(load,[]));if(loading)return <Loading/>;return <View style={s.root}><AppHeader title="My Rides" subtitle="Bookings and hosted trips" navigation={navigation}/><View style={s.tabs}><Pressable onPress={()=>setTab('booked')} style={[s.tab,tab==='booked'&&s.tabActive]}><Text style={[s.tabText,tab==='booked'&&s.tabTextActive]}>Booked</Text></Pressable><Pressable onPress={()=>setTab('hosted')} style={[s.tab,tab==='hosted'&&s.tabActive]}><Text style={[s.tabText,tab==='hosted'&&s.tabTextActive]}>Hosted</Text></Pressable></View><ScrollView contentContainerStyle={s.content}>{tab==='booked'?<>{bookings.length===0?<Empty icon="ticket-outline" title="No bookings yet" copy="Find a ride and request a seat. Confirmed bookings will appear here." onPress={()=>navigation.navigate('FindRide')}/>:bookings.map(b=><Card key={b.id}><View style={s.statusRow}><Badge text={b.status} tone={b.status==='CONFIRMED'?'green':b.status==='CANCELLED'?'red':'amber'}/><Text style={s.amount}>₹{Math.round(b.amount||0)}</Text></View><RouteRow from={b.ride?.origin||'Pickup'} to={b.ride?.destination||'Drop'} time={b.ride?.departureTime?new Date(b.ride.departureTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):undefined}/><Text style={s.meta}>{b.ride?.host?.firstName?`Host: ${b.ride.host.firstName}`:'Host details available after confirmation'}</Text>{b.status==='CONFIRMED'&&b.ride?.trip&&<Button title={b.ride.trip.status==='IN_PROGRESS'?'Open Live Trip':'Trip Details'} icon="navigate" onPress={()=>navigation.navigate('LiveTrip',{tripId:b.ride.trip.id})}/>}</Card>)}</>:<>{rides.length===0?<Empty icon="car-outline" title="No hosted rides" copy="Complete KYC, add a verified vehicle and publish your first ride." onPress={()=>navigation.navigate('OfferRide')}/>:rides.map(r=><HostedCard key={r.id} ride={r} navigation={navigation} reload={load}/>)}</>}</ScrollView></View>}
function HostedCard({ride,navigation,reload}:any){const pending=(ride.requests||[]).filter((x:any)=>x.status==='PENDING');return <Card><View style={s.statusRow}><Badge text={ride.status} tone={ride.status==='OPEN'?'green':'gray'}/><Text style={s.meta}>{ride.availableSeats} seats</Text></View><RouteRow from={ride.origin} to={ride.destination} time={new Date(ride.departureTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}/><Text style={s.meta}>{ride.vehicle?.make} {ride.vehicle?.model} · {ride.vehicle?.registrationNumber}</Text>{pending.length>0&&<View style={s.requests}><Text style={s.requestTitle}>{pending.length} passenger request{pending.length>1?'s':''}</Text>{pending.map((r:any)=><View key={r.id} style={s.request}><View style={s.avatar}><Text style={s.avatarText}>{(r.rider?.firstName||'R')[0]}</Text></View><View style={{flex:1}}><Text style={s.riderName}>{r.rider?.firstName||'Rider'}</Text><Text style={s.meta}>{r.seats} seat · ★ {r.rider?.rating?Number(r.rider.rating).toFixed(1):'New'}</Text></View><Pressable style={s.accept} onPress={async()=>{try{await requestApi.accept(r.id);reload()}catch(e:any){Alert.alert('Cannot accept',e.message)}}}><Text style={s.acceptText}>Accept</Text></Pressable></View>)}</View>} {ride.trip&&<Button title={ride.trip.status==='SCHEDULED'?'Start Trip':'Open Live Trip'} icon="navigate" onPress={()=>navigation.navigate('LiveTrip',{tripId:ride.trip.id})}/>}</Card>}
function Empty({icon,title,copy,onPress}:any){return <Card style={s.empty}><Ionicons name={icon} size={38} color={colors.green}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.meta}>{copy}</Text><Button title="Continue" onPress={onPress}/></Card>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},tabs:{margin:16,padding:4,borderRadius:14,backgroundColor:'#E9F0ED',flexDirection:'row'},tab:{flex:1,paddingVertical:11,borderRadius:11,alignItems:'center'},tabActive:{backgroundColor:'#fff'},tabText:{fontWeight:'800',color:colors.muted},tabTextActive:{color:colors.navy},content:{paddingHorizontal:16,paddingBottom:30},statusRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},amount:{fontSize:17,fontWeight:'900',color:colors.greenDark},meta:{fontSize:11,color:colors.muted,lineHeight:17},requests:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:colors.border},requestTitle:{fontSize:13,fontWeight:'900',color:colors.navy,marginBottom:8},request:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:8},avatar:{width:38,height:38,borderRadius:19,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900'},riderName:{fontWeight:'900',color:colors.navy},accept:{backgroundColor:colors.green,borderRadius:10,paddingHorizontal:12,paddingVertical:9},acceptText:{color:'#fff',fontSize:11,fontWeight:'900'},empty:{alignItems:'center',paddingVertical:30},emptyTitle:{fontSize:18,fontWeight:'900',color:colors.navy,marginTop:10}});
