import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Input,Loading} from '../components/ui';
import {colors} from '../theme/theme';
import {rideApi,userApi,vehicleApi} from '../api/services';

export default function OfferRideScreen({navigation}:any){
 const [step,setStep]=useState(1);const [vehicles,setVehicles]=useState<any[]>([]);const [vehicleId,setVehicleId]=useState('');const [origin,setOrigin]=useState('');const [destination,setDestination]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('08:30');const [seats,setSeats]=useState('3');const [price,setPrice]=useState('80');const [womenOnly,setWomenOnly]=useState(false);const [onboarding,setOnboarding]=useState<any>();const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([vehicleApi.list(),userApi.onboarding()]).then(([v,o])=>{setVehicles(v);setOnboarding(o);if(v[0])setVehicleId(v[0].id)}).catch(e=>Alert.alert('Could not load setup',e.message)).finally(()=>setLoading(false))},[]);
 const selected=vehicles.find(v=>v.id===vehicleId);const canOffer=onboarding?.canOffer;
 const publish=async()=>{if(!origin||!destination||!date||!vehicleId)return Alert.alert('Complete ride details','Add route, date and vehicle.');try{const iso=new Date(`${date}T${time}:00`).toISOString();const r=await rideApi.create({vehicleId,origin,destination,departureTime:iso,availableSeats:Number(seats),price:Number(price),womenOnly});Alert.alert('Ride published','Your ride is live. Passenger requests will appear in My Rides.');navigation.navigate('MyRides');}catch(e:any){Alert.alert('Could not publish',e.message)}};
 if(loading)return <Loading/>;
 return <View style={s.root}><AppHeader title="Offer a Ride" subtitle="Share your empty seats" navigation={navigation} showBack/><ScrollView contentContainerStyle={s.content}>
  <View style={s.stepper}>{[1,2,3].map(n=><View key={n} style={s.stepItem}><View style={[s.stepCircle,n<=step&&s.stepActive]}><Text style={[s.stepNum,n<=step&&{color:'#fff'}]}>{n}</Text></View><Text style={[s.stepLabel,n<=step&&{color:colors.greenDark}] }>{n===1?'Route':n===2?'Vehicle':'Confirm'}</Text></View>)}</View>
  {!canOffer && <Card style={s.blocker}><Ionicons name="shield-checkmark" size={28} color={colors.greenDark}/><View style={{flex:1}}><Text style={s.blockerTitle}>Complete verification before publishing</Text><Text style={s.blockerCopy}>WayMate requires verified KYC, driving licence, RC and active insurance.</Text></View><Button title="Verify" secondary onPress={()=>navigation.navigate('Kyc')}/></Card>}
  {step===1 && <Card><Text style={s.title}>Where are you going?</Text><Text style={s.copy}>Tell commuters your route and departure time.</Text><Input label="FROM" icon="location-outline" placeholder="HSR Layout, Bengaluru" value={origin} onChangeText={setOrigin}/><Input label="TO" icon="navigate-outline" placeholder="Whitefield, Bengaluru" value={destination} onChangeText={setDestination}/><Input label="DATE" icon="calendar-outline" placeholder="YYYY-MM-DD" value={date} onChangeText={setDate}/><Input label="DEPARTURE" icon="time-outline" placeholder="08:30" value={time} onChangeText={setTime}/><Button title="Next: Vehicle" icon="arrow-forward" disabled={!origin||!destination||!date} onPress={()=>setStep(2)}/></Card>}
  {step===2 && <Card><Text style={s.title}>Choose your verified vehicle</Text><Text style={s.copy}>Only vehicles with approved RC and active insurance can go live.</Text>{vehicles.length===0?<Card><Text style={s.copy}>No vehicles yet. Add a vehicle and upload its RC and insurance.</Text><Button title="Open Vehicles" onPress={()=>navigation.navigate('Vehicles')}/></Card>:vehicles.map(v=><Pressable key={v.id} onPress={()=>setVehicleId(v.id)} style={[s.vehicleCard,vehicleId===v.id&&s.vehicleSelected]}><View style={s.vehicleIcon}><Ionicons name={v.type==='BIKE'?'bicycle':'car'} size={23} color={colors.greenDark}/></View><View style={{flex:1}}><Text style={s.vehicleName}>{v.make} {v.model}</Text><Text style={s.vehicleMeta}>{v.registrationNumber} · {v.color||'—'}</Text><View style={{flexDirection:'row',gap:6,marginTop:6}}>{v.verified?<Badge text="Verified" icon="checkmark-circle"/>:<Badge text="Verification pending" tone="amber"/>}</View></View>{vehicleId===v.id&&<Ionicons name="checkmark-circle" size={24} color={colors.green}/>}</Pressable>)}<View style={s.seatRow}><View style={{flex:1}}><Text style={s.fieldTitle}>Available seats</Text><Text style={s.copy}>Seats excluding you</Text></View><Button secondary title="−" disabled={Number(seats)<=1} onPress={()=>setSeats(String(Math.max(1,Number(seats)-1)))}/><Text style={s.seatCount}>{seats}</Text><Button secondary title="+" disabled={Number(seats)>=6} onPress={()=>setSeats(String(Math.min(6,Number(seats)+1)))}/></View><View style={s.navButtons}><View style={{flex:1}}><Button secondary title="Back" onPress={()=>setStep(1)}/></View><View style={{flex:1}}><Button title="Next: Confirm" disabled={!vehicleId||!selected?.verified} onPress={()=>setStep(3)}/></View></View></Card>}
  {step===3 && <Card><Text style={s.title}>Review your ride</Text><Text style={s.copy}>Everything is checked on the server again when you publish.</Text><View style={s.review}><Text style={s.reviewLabel}>ROUTE</Text><Text style={s.reviewValue}>{origin} → {destination}</Text><Text style={s.reviewLabel}>DEPARTURE</Text><Text style={s.reviewValue}>{date} · {time}</Text><Text style={s.reviewLabel}>VEHICLE</Text><Text style={s.reviewValue}>{selected?.make} {selected?.model} · {selected?.registrationNumber}</Text><Text style={s.reviewLabel}>SEATS</Text><Text style={s.reviewValue}>{seats} passengers</Text></View><Input label="PRICE PER SEAT" icon="cash-outline" keyboardType="numeric" value={price} onChangeText={setPrice}/><Pressable style={s.womenToggle} onPress={()=>setWomenOnly(!womenOnly)}><Ionicons name={womenOnly?'shield-checkmark':'shield-outline'} size={20} color={womenOnly?colors.greenDark:colors.muted}/><View style={{flex:1}}><Text style={s.fieldTitle}>Women Safety Ride</Text><Text style={s.copy}>Only enable if you meet WayMate's women-host policy.</Text></View><View style={[s.switch,{backgroundColor:womenOnly?colors.green:'#D5DEDA'}]}><View style={[s.knob,womenOnly&&{marginLeft:18}]}/></View></Pressable><View style={s.navButtons}><View style={{flex:1}}><Button secondary title="Back" onPress={()=>setStep(2)}/></View><View style={{flex:1}}><Button title="Publish Ride" icon="checkmark" disabled={!canOffer||!selected?.verified} onPress={publish}/></View></View></Card>}
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:16,paddingBottom:32},stepper:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:28,paddingVertical:12},stepItem:{alignItems:'center'},stepCircle:{width:32,height:32,borderRadius:16,backgroundColor:'#E4ECE8',alignItems:'center',justifyContent:'center'},stepActive:{backgroundColor:colors.green},stepNum:{fontWeight:'900',color:colors.muted},stepLabel:{fontSize:10,fontWeight:'800',color:colors.muted,marginTop:5},blocker:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:colors.greenPale},blockerTitle:{fontWeight:'900',color:colors.navy},blockerCopy:{fontSize:11,lineHeight:16,color:colors.muted,marginTop:3},title:{fontSize:22,fontWeight:'900',color:colors.navy},copy:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:5,marginBottom:14},vehicleCard:{borderWidth:1,borderColor:colors.border,borderRadius:16,padding:14,marginTop:10,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#fff'},vehicleSelected:{borderColor:colors.green,backgroundColor:colors.greenPale},vehicleIcon:{width:44,height:44,borderRadius:13,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},vehicleName:{fontWeight:'900',color:colors.navy},vehicleMeta:{fontSize:11,color:colors.muted,marginTop:3},seatRow:{flexDirection:'row',alignItems:'center',marginTop:18,gap:10},fieldTitle:{fontWeight:'900',color:colors.navy},seatCount:{fontSize:18,fontWeight:'900',color:colors.navy,minWidth:24,textAlign:'center'},navButtons:{flexDirection:'row',gap:10,marginTop:12},review:{backgroundColor:colors.greenPale,borderRadius:15,padding:14,marginVertical:12},reviewLabel:{fontSize:9,fontWeight:'900',color:colors.muted,marginTop:8},reviewValue:{fontSize:14,fontWeight:'800',color:colors.navy,marginTop:3},womenToggle:{padding:14,borderRadius:15,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:10},switch:{width:38,height:22,borderRadius:11,padding:3},knob:{width:16,height:16,borderRadius:8,backgroundColor:'#fff'}});
