import React,{useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '../auth/AuthContext';
import {userApi} from '../api/services';
import {Button,Card,Input} from '../components/ui';
import {colors} from '../theme/theme';
export default function ProfileSetupScreen(){const {profile,refresh}=useAuth();const [first,setFirst]=useState(profile?.firstName||'');const [last,setLast]=useState(profile?.lastName||'');const [gender,setGender]=useState(profile?.gender||'');const [email,setEmail]=useState(profile?.email||'');const save=async()=>{if(!first.trim()||!last.trim()||!gender)return Alert.alert('Complete your profile','Name and gender are required to use the WayMate safety and matching system.');try{await userApi.update({firstName:first.trim(),lastName:last.trim(),gender,email:email.trim()});await refresh()}catch(e:any){Alert.alert('Could not save profile',e.message)}};return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.eyebrow}>WELCOME TO WAYMATE</Text><Text style={s.title}>A better commute{`\n`}starts with a verified profile.</Text><Text style={s.copy}>Your account can both find rides and offer rides. We'll use these details for matching and safety checks.</Text><Card><Input label="FIRST NAME" icon="person-outline" value={first} onChangeText={setFirst}/><Input label="LAST NAME" icon="person-outline" value={last} onChangeText={setLast}/><Input label="EMAIL" icon="mail-outline" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Text style={s.label}>GENDER</Text><View style={s.genderRow}>{[['FEMALE','woman'],['MALE','man'],['OTHER','person']].map(([v,i])=><Pressable key={v} onPress={()=>setGender(v)} style={[s.gender,gender===v&&s.genderActive]}><Ionicons name={i as any} size={17} color={gender===v?'#fff':colors.greenDark}/><Text style={[s.genderText,gender===v&&{color:'#fff'}]}>{v[0]+v.slice(1).toLowerCase()}</Text></Pressable>)}</View></Card><Button title="Continue" icon="arrow-forward" onPress={save}/><Text style={s.note}>Gender is used only where needed for matching and WayMate safety policy.</Text></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:22,paddingTop:55,paddingBottom:35},eyebrow:{fontSize:10,fontWeight:'900',color:colors.greenDark,letterSpacing:1},title:{fontSize:29,lineHeight:34,fontWeight:'900',color:colors.navy,marginTop:10},copy:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8,marginBottom:18},label:{fontSize:12,color:colors.muted,fontWeight:'800',marginBottom:8},genderRow:{flexDirection:'row',gap:8},gender:{flex:1,minHeight:46,borderRadius:13,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',gap:5},genderActive:{backgroundColor:colors.green,borderColor:colors.green},genderText:{fontSize:11,fontWeight:'900',color:colors.navy},note:{fontSize:10,lineHeight:15,color:colors.muted,textAlign:'center',marginTop:10}});
