import React,{useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '../auth/AuthContext';
import {userApi} from '../api/services';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Input} from '../components/ui';
import {colors} from '../theme/theme';

export default function ProfileScreen({navigation}:any){const {profile,logout,refresh}=useAuth();const [first,setFirst]=useState(profile?.firstName||'');const [last,setLast]=useState(profile?.lastName||'');const verified=profile?.kycStatus==='VERIFIED';const save=async()=>{try{await userApi.update({firstName:first.trim(),lastName:last.trim(),gender:profile?.gender,email:profile?.email||''});await refresh();Alert.alert('Profile saved')}catch(e:any){Alert.alert('Could not save',e.message)}};const items=[['shield-checkmark','Identity & KYC','Verify your identity and driving licence','Kyc'],['car-outline','Vehicles & documents','RC, insurance and verification','Vehicles'],['wallet-outline','Wallet & Bank Payouts','Manage your earnings and bank details','Wallet'],['shield-half','Safety Centre','Women Safety Mode and emergency contacts','Safety'],['car-sport-outline','My Hosted Rides','Manage requests and passengers','MyRides']];return <View style={s.root}><AppHeader title="My Profile" subtitle="Your WayMate account" navigation={navigation}/><ScrollView contentContainerStyle={s.content}><View style={s.profileHero}><View style={s.avatar}><Text style={s.avatarText}>{(profile?.firstName||'W')[0]}</Text></View><Text style={s.name}>{profile?.firstName||'WayMate User'} {profile?.lastName||''}</Text><Text style={s.phone}>{profile?.phone||profile?.email||''}</Text><Badge text={verified?'Verified user':`KYC ${profile?.kycStatus||'UNVERIFIED'}`} icon={verified?'checkmark-circle':'shield-checkmark'} tone={verified?'green':'amber'}/></View><Card><Text style={s.cardTitle}>Personal details</Text><Input label="FIRST NAME" value={first} onChangeText={setFirst}/><Input label="LAST NAME" value={last} onChangeText={setLast}/><Button title="Save changes" onPress={save}/></Card>{items.map(([icon,title,sub,target])=><Pressable key={title} onPress={()=>navigation.navigate(target)} style={s.menu}><View style={s.menuIcon}><Ionicons name={icon as any} size={21} color={colors.greenDark}/></View><View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>)}<Button secondary title="Sign out" icon="log-out-outline" onPress={logout}/><Text style={s.version}>WayMate · Android launch build</Text><Card><Pressable onPress={()=>navigation.navigate('Support')} style={{flexDirection:'row',alignItems:'center',gap:12}}><Ionicons name="headset" size={22} color={colors.greenDark}/><View style={{flex:1}}><Text style={{fontWeight:'900',color:colors.navy}}>Help & Support</Text><Text style={{fontSize:11,color:colors.muted,marginTop:3}}>+91 7259335286</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable></Card></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:16,paddingBottom:35},profileHero:{alignItems:'center',paddingVertical:18},avatar:{width:82,height:82,borderRadius:41,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:32,fontWeight:'900',color:'#fff'},name:{fontSize:22,fontWeight:'900',color:colors.navy,marginTop:10},phone:{fontSize:12,color:colors.muted,marginVertical:4},cardTitle:{fontSize:17,fontWeight:'900',color:colors.navy,marginBottom:12},menu:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:16,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12},menuIcon:{width:44,height:44,borderRadius:13,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},menuTitle:{fontSize:14,fontWeight:'900',color:colors.navy},menuSub:{fontSize:11,color:colors.muted,marginTop:3},version:{fontSize:10,color:colors.muted,textAlign:'center',marginTop:12}});
