import React,{useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '../auth/AuthContext';
import {userApi} from '../api/services';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Input} from '../components/ui';
import {colors} from '../theme/theme';

export default function ProfileScreen({navigation}:any){const {profile,logout,refresh}=useAuth();const [first,setFirst]=useState(profile?.firstName||'');const [last,setLast]=useState(profile?.lastName||'');const verified=profile?.kycStatus==='VERIFIED';const save=async()=>{try{await userApi.update({firstName:first.trim(),lastName:last.trim(),gender:profile?.gender,email:profile?.email||''});await refresh();Alert.alert('Profile saved')}catch(e:any){Alert.alert('Could not save',e.message)}};const items=[['shield-checkmark','Identity & KYC','Verify your identity and driving licence','Kyc'],['car-outline','Vehicles & documents','RC, insurance and verification','Vehicles'],['wallet-outline','Wallet & Bank Payouts','Manage your earnings and bank details','Wallet'],['shield-half','Safety Centre','Women Safety Mode and emergency contacts','Safety'],['car-sport-outline','My Hosted Rides','Manage requests and passengers','MyRides']];return <View style={s.root}><AppHeader title="My Profile" subtitle="Your WayMate account" navigation={navigation}/><ScrollView contentContainerStyle={s.content}><View style={s.profileHero}><View style={s.avatar}><Text style={s.avatarText}>{(profile?.firstName||'W')[0]}</Text></View><Text style={s.name}>{profile?.firstName||'WayMate User'} {profile?.lastName||''}</Text><Text style={s.phone}>{profile?.phone||profile?.email||''}</Text><Badge text={verified?'Verified user':`KYC ${profile?.kycStatus||'UNVERIFIED'}`} icon={verified?'checkmark-circle':'shield-checkmark'} tone={verified?'green':'amber'}/></View><Card><Text style={s.cardTitle}>Personal details</Text><Input label="FIRST NAME" value={first} onChangeText={setFirst}/><Input label="LAST NAME" value={last} onChangeText={setLast}/><Button title="Save changes" onPress={save}/></Card>{items.map(([icon,title,sub,target])=><Pressable key={title} onPress={()=>navigation.navigate(target)} style={s.menu}><View style={s.menuIcon}><Ionicons name={icon as any} size={22} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>)}<Button secondary title="Sign out" icon="log-out-outline" onPress={logout}/><Text style={s.version}>WayMate · Android launch build</Text><Card><Pressable onPress={()=>navigation.navigate('Support')} style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={s.menuIcon}><Ionicons name="headset" size={22} color={colors.primary}/></View><View style={{flex:1}}><Text style={{fontWeight:'800',color:colors.navy2,fontSize:16}}>Help & Support</Text><Text style={{fontSize:13,color:colors.muted,marginTop:4}}>Contact our 24/7 team</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable></Card></ScrollView></View>}
import {colors, shadows} from '../theme/theme';

const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:20,paddingBottom:40},profileHero:{alignItems:'center',paddingVertical:24},avatar:{width:96,height:96,borderRadius:48,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',...shadows.md},avatarText:{fontSize:38,fontWeight:'900',color:'#fff'},name:{fontSize:24,fontWeight:'800',color:colors.navy2,marginTop:16,letterSpacing:-0.5},phone:{fontSize:15,fontWeight:'600',color:colors.muted,marginVertical:8},cardTitle:{fontSize:18,fontWeight:'800',color:colors.navy2,marginBottom:16},menu:{backgroundColor:'#fff',borderRadius:20,padding:16,marginBottom:12,flexDirection:'row',alignItems:'center',gap:14,...shadows.sm},menuIcon:{width:48,height:48,borderRadius:24,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},menuTitle:{fontSize:16,fontWeight:'700',color:colors.navy2},menuSub:{fontSize:13,color:colors.muted,marginTop:4,fontWeight:'500'},version:{fontSize:12,color:colors.mutedLight,textAlign:'center',marginTop:20,marginBottom:20,fontWeight:'600'}});
