import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Loading,RouteRow} from '../components/ui';
import {colors} from '../theme/theme';
import {rideApi} from '../api/services';

export default function RideDetailsScreen({route,navigation}:any){const [ride,setRide]=useState<any>();const [loading,setLoading]=useState(true);const [seats,setSeats]=useState(1);useEffect(()=>{rideApi.get(route.params.rideId).then(setRide).catch(e=>Alert.alert('Could not load ride',e.message)).finally(()=>setLoading(false))},[]);if(loading)return <Loading/>;if(!ride)return null;const hostFemale=ride.host?.gender==='FEMALE';const femaleRiders=(ride.bookings||[]).filter((b:any)=>b.rider?.gender==='FEMALE').length;const safetyWarning=ride.womenOnly || (!hostFemale && femaleRiders<1);async function request(){try{await rideApi.request(ride.id,seats);Alert.alert('Request sent','Your seat request is now with the host. We will show the booking status in My Rides.');navigation.navigate('MyRides')}catch(e:any){Alert.alert(e.code==='FEMALE_COMPANION_REQUIRED'?'Women Safety Check':'Booking failed',e.message)}}return <View style={s.root}><AppHeader title="Ride Details" navigation={navigation} showBack/><ScrollView contentContainerStyle={s.content}><Card style={s.routeCard}><View style={s.routeHead}><Badge text={ride.status==='OPEN'?'Seats available':'Not available'} tone={ride.status==='OPEN'?'green':'red'}/>{ride.womenOnly&&<Badge text="Women Safety Ride" icon="shield-checkmark"/>}</View><RouteRow from={ride.origin} to={ride.destination} time={new Date(ride.departureTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}/><View style={s.routeMeta}><View><Text style={s.metaLabel}>DATE</Text><Text style={s.metaValue}>{new Date(ride.departureTime).toLocaleDateString()}</Text></View><View><Text style={s.metaLabel}>SEATS</Text><Text style={s.metaValue}>{ride.availableSeats} left</Text></View><View><Text style={s.metaLabel}>PRICE</Text><Text style={s.price}>₹{Math.round(ride.price)}</Text></View></View></Card>
<Card><View style={s.hostRow}><View style={s.avatar}><Text style={s.avatarText}>{(ride.host?.firstName||'W')[0]}</Text></View><View style={{flex:1}}><Text style={s.hostName}>{ride.host?.firstName||'WayMate host'} {ride.host?.lastName||''}</Text><Text style={s.rating}>★ {ride.host?.rating?Number(ride.host.rating).toFixed(1):'New'} · {ride.host?.ratingCount||0} ratings</Text></View>{ride.host?.verified&&<Badge text="Verified" icon="checkmark-circle"/>}</View><View style={s.divider}/><Text style={s.cardTitle}>Vehicle</Text><View style={s.vehicleRow}><Ionicons name={ride.vehicle?.type==='BIKE'?'bicycle':'car-outline'} size={25} color={colors.navy}/><View style={{flex:1}}><Text style={s.vehicleName}>{ride.vehicle?.make} {ride.vehicle?.model}</Text><Text style={s.vehicleMeta}>{ride.vehicle?.color||'—'} · {ride.vehicle?.registrationNumber}</Text></View>{ride.vehicle?.verified?<Badge text="RC + Insurance" icon="shield-checkmark" tone="green"/>:<Badge text="Pending" tone="amber"/>}</View></Card>
<Card><Text style={s.cardTitle}>Women Safety Check</Text><Text style={s.safetyCopy}>WayMate checks host verification, vehicle verification and confirmed female companion requirements according to the active safety policy.</Text>{safetyWarning?<View style={s.warning}><Ionicons name="shield" size={20} color={colors.amber}/><View style={{flex:1}}><Text style={s.warningTitle}>Safety precaution</Text><Text style={s.warningCopy}>{hostFemale?'Verified female host is available for this ride.':'If a female rider is travelling with a male host, WayMate may require another confirmed female rider under the active policy.'}</Text></View></View>:<Badge text="Safety checks passed for current booking state" icon="shield-checkmark"/>}</Card>
<Card><Text style={s.cardTitle}>Choose your seats</Text><View style={s.seatRow}><Button secondary title="−" disabled={seats<=1} onPress={()=>setSeats(Math.max(1,seats-1))}/><View style={s.seatCount}><Text style={s.seatNumber}>{seats}</Text><Text style={s.per}>seat{seats>1?'s':''}</Text></View><Button secondary title="+" disabled={seats>=Math.min(ride.availableSeats,6)} onPress={()=>setSeats(Math.min(ride.availableSeats,6))}/></View><Text style={s.total}>Total ₹{Math.round(ride.price*seats)}</Text><Button title="Request Seat" icon="ticket" disabled={ride.availableSeats<seats} onPress={request}/><Text style={s.small}>Your booking is only confirmed after the host accepts your request.</Text></Card></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:16,paddingBottom:30},routeCard:{padding:18},routeHead:{flexDirection:'row',gap:6,marginBottom:10},routeMeta:{borderTopWidth:1,borderTopColor:colors.border,marginTop:10,paddingTop:14,flexDirection:'row',justifyContent:'space-between'},metaLabel:{fontSize:9,color:colors.muted,fontWeight:'800'},metaValue:{fontSize:13,color:colors.navy,fontWeight:'900',marginTop:3},price:{fontSize:15,color:colors.greenDark,fontWeight:'900',marginTop:3},hostRow:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:50,height:50,borderRadius:25,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:20,color:'#fff',fontWeight:'900'},hostName:{fontSize:16,color:colors.navy,fontWeight:'900'},rating:{fontSize:11,color:colors.muted,marginTop:3},divider:{height:1,backgroundColor:colors.border,marginVertical:15},cardTitle:{fontSize:16,color:colors.navy,fontWeight:'900'},vehicleRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:12},vehicleName:{fontWeight:'900',color:colors.text},vehicleMeta:{fontSize:11,color:colors.muted,marginTop:3},safetyCopy:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:6},warning:{flexDirection:'row',gap:10,padding:12,borderRadius:14,backgroundColor:colors.amberSoft,marginTop:12},warningTitle:{fontWeight:'900',color:colors.navy},warningCopy:{fontSize:11,lineHeight:17,color:colors.muted,marginTop:3},seatRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:18,marginTop:14},seatCount:{alignItems:'center',minWidth:65},seatNumber:{fontSize:28,fontWeight:'900',color:colors.navy},per:{fontSize:10,color:colors.muted},total:{textAlign:'center',fontSize:20,fontWeight:'900',color:colors.greenDark,marginVertical:10},small:{fontSize:10,color:colors.muted,textAlign:'center',lineHeight:15}});
