import React,{useEffect,useState} from 'react';
import {Alert,FlatList,StyleSheet,Text,View,Pressable} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import AppHeader from '../components/AppHeader';
import {Badge,Card,Loading} from '../components/ui';
import {colors} from '../theme/theme';
import {rideApi} from '../api/services';

export default function RideResultsScreen({navigation,route}:any){const {origin,destination,date,womenOnly}=route.params;const [rides,setRides]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{rideApi.search({origin,destination,date,womenOnly}).then(setRides).catch(e=>Alert.alert('Search failed',e.message)).finally(()=>setLoading(false))},[]);return <View style={s.root}><AppHeader title="Rides Found" subtitle={`${origin} → ${destination}`} navigation={navigation} showBack/>{loading?<Loading label="Finding verified rides…"/>:<FlatList data={rides} contentContainerStyle={s.list} keyExtractor={x=>x.id} ListHeaderComponent={<View style={s.resultHeader}><Text style={s.count}>{rides.length} {rides.length===1?'ride':'rides'} found</Text><Text style={s.sort}>Earliest first</Text></View>} ListEmptyComponent={<Card><Ionicons name="car-outline" size={34} color={colors.muted}/><Text style={s.emptyTitle}>No rides found yet</Text><Text style={s.emptyCopy}>Try another date, nearby pickup or destination. Results are always live from WayMate.</Text></Card>} renderItem={({item})=><Pressable onPress={()=>navigation.navigate('RideDetails',{rideId:item.id})}><Card style={s.rideCard}><View style={s.top}><View style={s.avatar}><Text style={s.avatarText}>{(item.host?.firstName||'W')[0]}</Text></View><View style={{flex:1}}><Text style={s.host}>{item.host?.firstName||'WayMate host'}</Text><Text style={s.rating}>★ {item.host?.rating?Number(item.host.rating).toFixed(1):'New'} · {item.host?.ratingCount||0} rides</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.price}>₹{Math.round(item.price)}</Text><Text style={s.per}>per seat</Text></View></View><View style={s.routeBox}><Text style={s.routeMain}>{item.origin} → {item.destination}</Text><Text style={s.depart}>{new Date(item.departureTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · {item.availableSeats} seats left</Text></View><View style={s.tags}>{item.host?.verified&&<Badge text="Verified" icon="checkmark-circle"/>}{item.vehicle?.verified&&<Badge text="Vehicle verified" icon="car" tone="blue"/>}{item.womenOnly&&<Badge text="Women Safety" icon="shield-checkmark"/>}</View><View style={s.vehicle}><Ionicons name={item.vehicle?.type==='BIKE'?'bicycle':'car-outline'} size={20} color={colors.navy}/><Text style={s.vehicleText}>{item.vehicle?.make} {item.vehicle?.model} · {item.vehicle?.color||'Vehicle'}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></View></Card></Pressable>}/>}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},list:{padding:16,paddingBottom:28},resultHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},count:{fontSize:16,fontWeight:'900',color:colors.navy},sort:{fontSize:11,color:colors.greenDark,fontWeight:'800'},rideCard:{padding:16},top:{flexDirection:'row',alignItems:'center'},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900',fontSize:18},host:{fontWeight:'900',color:colors.navy,fontSize:15},rating:{fontSize:11,color:colors.muted,marginTop:3},price:{fontSize:20,fontWeight:'900',color:colors.greenDark},per:{fontSize:10,color:colors.muted},routeBox:{marginTop:14,padding:12,borderRadius:14,backgroundColor:colors.greenPale},routeMain:{fontWeight:'900',color:colors.navy,fontSize:14},depart:{fontSize:11,color:colors.muted,marginTop:5},tags:{flexDirection:'row',gap:6,flexWrap:'wrap',marginTop:12},vehicle:{borderTopWidth:1,borderTopColor:colors.border,marginTop:12,paddingTop:12,flexDirection:'row',alignItems:'center',gap:8},vehicleText:{flex:1,fontSize:12,color:colors.text,fontWeight:'700'},emptyTitle:{fontSize:17,fontWeight:'900',color:colors.navy,marginTop:10},emptyCopy:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:4}});
