import React,{useCallback,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View,Pressable} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import AppHeader from '../components/AppHeader';
import {Badge,Button,Card,Input,Loading} from '../components/ui';
import {colors} from '../theme/theme';
import {vehicleApi} from '../api/services';
export default function VehiclesScreen({navigation}:any){const [vehicles,setVehicles]=useState<any[]>([]);const [type,setType]=useState<'CAR'|'BIKE'>('CAR');const [make,setMake]=useState('');const [model,setModel]=useState('');const [reg,setReg]=useState('');const [seats,setSeats]=useState('4');const [expiry,setExpiry]=useState('');const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);vehicleApi.list().then(setVehicles).catch(e=>Alert.alert('Vehicles',e.message)).finally(()=>setLoading(false))};useFocusEffect(useCallback(load,[]));async function upload(id:string,docType:'RC'|'INSURANCE'){try{const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,type:['image/*','application/pdf']});if(r.canceled)return;const a=r.assets[0];await vehicleApi.uploadDocument(id,docType,{uri:a.uri,name:a.name,type:a.mimeType||'application/octet-stream'});Alert.alert('Uploaded','The document is now pending WayMate verification.');load()}catch(e:any){Alert.alert('Upload failed',e.message)}}async function add(){if(!make||!model||!reg||!expiry)return Alert.alert('Complete vehicle details','Add make, model, registration and insurance expiry.');try{await vehicleApi.create({type,make,model,registrationNumber:reg.toUpperCase(),seats:Number(seats),insuranceExpiry:new Date(`${expiry}T23:59:59`).toISOString()});setMake('');setModel('');setReg('');setExpiry('');load()}catch(e:any){Alert.alert('Could not add vehicle',e.message)}}if(loading)return <Loading/>;return <View style={s.root}><AppHeader title="Vehicles" subtitle="RC + insurance verification" navigation={navigation} showBack/><ScrollView contentContainerStyle={s.content}>{vehicles.length>0&&<><Text style={s.section}>Your vehicles</Text>{vehicles.map(v=><Card key={v.id}><View style={s.head}><View style={s.icon}><Ionicons name={v.type==='BIKE'?'bicycle':'car'} size={23} color={colors.greenDark}/></View><View style={{flex:1}}><Text style={s.name}>{v.make} {v.model}</Text><Text style={s.meta}>{v.registrationNumber} · {v.seats} seats</Text></View><Badge text={v.verified?'Verified':'Pending'} icon={v.verified?'checkmark-circle':'time'} tone={v.verified?'green':'amber'}/></View><View style={s.docs}><Doc label="RC" status={v.documents?.find((d:any)=>d.type==='RC')?.status}/><Doc label="Insurance" status={v.documents?.find((d:any)=>d.type==='INSURANCE')?.status}/></View><View style={s.buttons}><View style={{flex:1}}><Button secondary title="Upload RC" onPress={()=>upload(v.id,'RC')}/></View><View style={{flex:1}}><Button secondary title="Upload Insurance" onPress={()=>upload(v.id,'INSURANCE')}/></View></View></Card>)}</>}
<Card><Text style={s.title}>Add a vehicle</Text><Text style={s.copy}>You need a verified RC and active insurance before you can publish a ride.</Text><View style={s.typeRow}>{[['CAR','car'],['BIKE','bicycle']].map(([v,i])=><Pressable key={v} onPress={()=>setType(v as any)} style={[s.typeButton,type===v&&s.typeActive]}><Ionicons name={i as any} size={19} color={type===v?'#fff':colors.greenDark}/><Text style={[s.typeText,type===v&&{color:'#fff'}]}>{v}</Text></Pressable>)}</View><Input label="MAKE" value={make} onChangeText={setMake} placeholder="Hyundai"/><Input label="MODEL" value={model} onChangeText={setModel} placeholder="Creta"/><Input label="REGISTRATION" value={reg} onChangeText={setReg} placeholder="KA 51 XX 1234" autoCapitalize="characters"/><Input label="INSURANCE EXPIRY" value={expiry} onChangeText={setExpiry} placeholder="YYYY-MM-DD"/><Input label="AVAILABLE SEATS" keyboardType="number-pad" value={seats} onChangeText={setSeats}/><Button title="Add vehicle" icon="add" onPress={add}/></Card><Text style={s.note}>Documents are stored securely and reviewed by authorized WayMate operations staff.</Text></ScrollView></View>}
function Doc({label,status}:any){return <View style={s.doc}><Text style={s.docLabel}>{label}</Text><Badge text={status||'Not uploaded'} tone={status==='VERIFIED'?'green':status==='REJECTED'?'red':'amber'}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:16,paddingBottom:30},section:{fontSize:20,fontWeight:'900',color:colors.navy,marginBottom:10},head:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:48,height:48,borderRadius:14,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'900',color:colors.navy},meta:{fontSize:11,color:colors.muted,marginTop:3},docs:{flexDirection:'row',gap:10,marginTop:14},doc:{flex:1,padding:10,borderRadius:12,backgroundColor:colors.bg},docLabel:{fontSize:10,fontWeight:'900',color:colors.muted,marginBottom:5},buttons:{flexDirection:'row',gap:8,marginTop:8},title:{fontSize:21,fontWeight:'900',color:colors.navy},copy:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:5,marginBottom:14},typeRow:{flexDirection:'row',gap:8,marginBottom:14},typeButton:{flex:1,minHeight:46,borderRadius:13,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},typeActive:{backgroundColor:colors.green,borderColor:colors.green},typeText:{fontSize:12,fontWeight:'900',color:colors.navy},note:{fontSize:10,lineHeight:15,color:colors.muted,textAlign:'center'}});
