import { api, apiMultipart } from './client';
export const userApi = { me:()=>api<any>('/users/me'), update:(d:any)=>api<any>('/users/me',{method:'PUT',body:JSON.stringify(d)}), onboarding:()=>api<any>('/onboarding/status') };
export const kycApi = { me:()=>api<any>('/kyc/me'), upload:(type:string,file:{uri:string,name:string,type:string})=>apiMultipart<any>('/kyc/documents',file,{type}), submit:()=>api<any>('/kyc/submit',{method:'POST'}) };
export const vehicleApi = { list:()=>api<any[]>('/vehicles'), create:(d:any)=>api<any>('/vehicles',{method:'POST',body:JSON.stringify(d)}), remove:(id:string)=>api<void>(`/vehicles/${id}`,{method:'DELETE'}), uploadDocument:(id:string,type:string,file:any)=>apiMultipart<any>(`/vehicles/${id}/documents`,file,{type}) };
export const rideApi = { popular:()=>api<any[]>('/rides/popular'), search:(p:any)=>api<any[]>(`/rides/search?${new URLSearchParams(p).toString()}`), my:()=>api<any[]>('/rides/my'), get:(id:string)=>api<any>(`/rides/${id}`), create:(d:any)=>api<any>('/rides',{method:'POST',body:JSON.stringify(d)}), request:(id:string,seats:number)=>api<any>(`/rides/${id}/request`,{method:'POST',body:JSON.stringify({seats})}) };
export const bookingApi = { my:()=>api<any[]>('/bookings/my'), cancel:(id:string)=>api<any>(`/bookings/${id}/cancel`,{method:'POST'}) };
export const requestApi = { my:()=>api<any[]>('/requests/my'), accept:(id:string)=>api<any>(`/requests/${id}/accept`,{method:'POST'}), reject:(id:string)=>api<any>(`/requests/${id}/reject`,{method:'POST'}) };
export const tripApi = { my:()=>api<any[]>('/trips/my'), get:(id:string)=>api<any>(`/trips/${id}`), start:(id:string)=>api<any>(`/trips/${id}/start`,{method:'POST'}), complete:(id:string)=>api<any>(`/trips/${id}/complete`,{method:'POST'}), cancel:(id:string)=>api<any>(`/trips/${id}/cancel`,{method:'POST'}), location:(id:string,d:any)=>api<any>(`/trips/${id}/location`,{method:'POST'}) };
export const safetyApi = { policy:()=>api<any>('/safety/policy'), contacts:()=>api<any[]>('/safety/emergency-contacts'), addContact:(d:any)=>api<any>('/safety/emergency-contacts',{method:'POST',body:JSON.stringify(d)}), report:(d:any)=>api<any>('/safety/report',{method:'POST',body:JSON.stringify(d)}),sos:(d:any)=>api<any>('/safety/sos',{method:'POST',body:JSON.stringify(d)}) };
