import React,{useEffect,useState} from 'react';
import {Alert,Linking,ScrollView,Text} from 'react-native';
import {safetyApi} from '../api/services';
import {Button,Card,Input} from '../components/ui';
import {colors} from '../theme/theme';
export default function SafetyScreen(){
 const [policy,setPolicy]=useState<any>();const [contacts,setContacts]=useState<any[]>([]);const [name,setName]=useState('');const [phone,setPhone]=useState('');
 useEffect(()=>{Promise.all([safetyApi.policy(),safetyApi.contacts()]).then(([p,c])=>{setPolicy(p);setContacts(c)}).catch(e=>Alert.alert('Safety',e.message))},[]);
 async function add(){try{const c=await safetyApi.addContact({name,phone,relation:'Emergency contact'});setContacts(x=>[...x,c]);setName('');setPhone('')}catch(e:any){Alert.alert('Safety',e.message)}}
 return <ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={{padding:18}}><Text style={{fontSize:30,fontWeight:'900',color:colors.navy}}>Safety Centre</Text><Text style={{color:colors.muted,marginBottom:16}}>Safety features are designed to reduce risk. They do not replace emergency services.</Text><Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Women Safety Mode</Text><Text style={{color:colors.muted,marginTop:6}}>Women-only rides require the safety checks configured by WayMate operations. For mixed rides, a female passenger may be required to have a verified female host or another confirmed female companion.</Text></Card><Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Before boarding</Text><Text>• Check host identity and verification badge.</Text><Text>• Confirm vehicle number matches the app.</Text><Text>• Share the trip with someone you trust.</Text><Text>• Use SOS if you feel unsafe.</Text></Card><Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Emergency contacts</Text>{contacts.map(c=><Text key={c.id} style={{marginTop:8}}>{c.name} · {c.phone}</Text>)}<Input label="Name" value={name} onChangeText={setName}/><Input label="Phone" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><Button title="Add emergency contact" onPress={add}/>{contacts[0]&&<Button secondary title="Call emergency contact" onPress={()=>Linking.openURL(`tel:${contacts[0].phone}`)}/>}</Card><Card><Text style={{fontSize:18,fontWeight:'900',color:colors.navy}}>Safety policy</Text><Text style={{color:colors.muted}}>KYC is required for booking under the current launch policy. Drivers need verified identity, driving licence, RC and active insurance before they can start trips.</Text></Card></ScrollView>
}
